[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /usr/home/admin/public_html/media/laravel12/artisan queue:work --sleep=3 --tries=3 --timeout=300
autostart=true
autorestart=true
user=admin
numprocs=1
redirect_stderr=true
stdout_logfile=/usr/home/admin/public_html/media/laravel12/storage/logs/worker.log
stopwaitsecs=3600
